version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing frontend dependencies..."
      - cd $CODEBUILD_SRC_DIR/frontend && npm install --legacy-peer-deps

  pre_build:
    commands:
      - echo "Starting frontend build..."
      - node -v
      - npm -v

  build:
    commands:
      - echo "Building React application..."
      - cd $CODEBUILD_SRC_DIR/frontend && npm run build

  post_build:
    commands:
      - echo "Frontend build completed successfully."

artifacts:
  files:
    - "**/*"
  base-directory: frontend/build
  name: staynest-frontend-$(date +%Y%m%d%H%M%S)

cache:
  paths:
    - frontend/node_modules/**/*
