version: 0.2

phases:
  pre_build:
    commands:
      - chmod +x pipeline/scripts/deploy-run.sh
      - pipeline/scripts/deploy-run.sh pre

  build:
    commands:
      - pipeline/scripts/deploy-run.sh build

  post_build:
    commands:
      - pipeline/scripts/deploy-run.sh post
